import type { Metadata } from "next";
import "@mantine/core/styles.css";
import {
  ColorSchemeScript,
  MantineProvider,
  mantineHtmlProps,
} from "@mantine/core";
import { AppShellContainer } from "@/components/AppShellContainer";
import StoreProvider from "./storeProvider";
import { Notifications } from "@mantine/notifications";

export const metadata: Metadata = {
  title: {
    default: "My Post Website",
    template: "%s | My Post Website",
  },
  description: "Generated by create next app",
  icons: "/favicon.ico",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript />
      </head>
      <body style={{ background: "var(--mantine-color-gray-light)" }}>
        <MantineProvider>
          <StoreProvider>
            <Notifications position="top-right" />
            <AppShellContainer>{children}</AppShellContainer>
          </StoreProvider>
        </MantineProvider>
      </body>
    </html>
  );
}
