import type { Metadata } from "next";
import '@mantine/core/styles.css'
import Header from "@/components/header";
import Footer from "@/components/footer";
import {
  Container,
  ColorSchemeScript,
  MantineProvider,
  mantineHtmlProps,
  AppShell,
  AppShellMain,
  AppShellHeader,
  AppShellFooter,
} from "@mantine/core";

export const metadata: Metadata = {
  title: {
    default: "My Posts",
    template: "%s | My Posts",
  },
  description: "Generated by create next app",
  icons: "/favicon.ico",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript />
        {/* <link rel="icon" href="/favicon.ico" sizes="any" /> */}
      </head>
      <body style={{ background: "#f5f4f4"}}>
        <MantineProvider>
          <Container
            maw={1100}
            mih="100vh"
            pos={"relative"}
            bg={"var(--mantine-color-white)"}
            style={{
              borderRight: "1px solid black",
              borderLeft: "1px solid black",
            }}
          >
            <AppShell header={{ height: 65 }} footer={{ height: 65 }} h="100%">
              <AppShellHeader pos={"absolute"}>
                <Header />
              </AppShellHeader>

              <AppShellMain>{children}</AppShellMain>

              <AppShellFooter pos={"absolute"}>
                <Footer />
              </AppShellFooter>
            </AppShell>
          </Container>
        </MantineProvider>
      </body>
    </html>
  );
}
